version: '3.8'

services:
  codeshare:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./public:/app/public:ro
    networks:
      - codeshare-network

networks:
  codeshare-network:
    driver: bridge